server {
  listen 80;
  server_name localhost;

  # Backend Fastify
  location /api/ {
    proxy_pass http://backend_app:3000/;  # 👈 usa el nombre del servicio backend en docker-compose
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
  }

  # Frontend React/Vite build
  location / {
    root /usr/share/nginx/html;
    index index.html;
    try_files $uri /index.html;
  }
}
